# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'linkedinScraperGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.launchButton = QtWidgets.QToolButton(self.centralwidget)
        self.launchButton.setGeometry(QtCore.QRect(440, 80, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.launchButton.setFont(font)
        self.launchButton.setObjectName("launchButton")
        self.email = QtWidgets.QTextEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(30, 80, 291, 41))
        self.email.setObjectName("email")
        self.password = QtWidgets.QTextEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(30, 160, 291, 41))
        self.password.setMarkdown("")
        self.password.setObjectName("password")
        self.searchbar = QtWidgets.QTextEdit(self.centralwidget)
        self.searchbar.setGeometry(QtCore.QRect(30, 240, 291, 41))
        self.searchbar.setObjectName("searchbar")
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(30, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(30, 130, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.password_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.password_label_2.setGeometry(QtCore.QRect(30, 210, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.password_label_2.setFont(font)
        self.password_label_2.setObjectName("password_label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linkedin Scraper"))
        self.launchButton.setText(_translate("MainWindow", "Let\'s go!"))
        self.email_label.setText(_translate("MainWindow", "LinkedIn e-mail address"))
        self.password_label.setText(_translate("MainWindow", "LinkedIn password"))
        self.password_label_2.setText(_translate("MainWindow", "Search to proceed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
